# Generated by Django 4.2.1 on 2023-06-03 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_body',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='content'),
            preserve_default=False,
        ),
    ]
