# Generated by Django 4.2.1 on 2023-06-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_comment_comment_body_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
