# Generated by Django 4.2.1 on 2023-06-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='article_id',
        ),
    ]
